/**
 * Interconnected sample documents for each Payload collection.
 *
 * Relationship fields use stable string placeholders (e.g. `user-couple-alex`).
 * When seeding, create docs in dependency order and rewrite placeholders to real IDs:
 *   media → users → vendors → weddings → guests → conversations → messages → payments
 * then backfill user.vendorAccount / wedding.selectedVendors / wedding.guestList as needed.
 */

export const sampleIds = {
  media: {
    avatarAlex: 'media-avatar-alex',
    avatarJordan: 'media-avatar-jordan',
    avatarMaya: 'media-avatar-maya',
    venueHero: 'media-venue-oaks-hero',
    venueGallery1: 'media-venue-oaks-gallery-1',
    venueGallery2: 'media-venue-oaks-gallery-2',
    floristHero: 'media-florist-petal-hero',
    photoHero: 'media-photo-lens-hero',
    catererHero: 'media-caterer-harvest-hero',
    musicHero: 'media-music-groove-hero',
    bakeryHero: 'media-bakery-sugar-hero',
    quotePdf: 'media-quote-attachment',
  },
  users: {
    admin: 'user-admin',
    coupleAlex: 'user-couple-alex',
    coupleJordan: 'user-couple-jordan',
    coupleSam: 'user-couple-sam',
    coupleRiley: 'user-couple-riley',
    vendorVenue: 'user-vendor-venue',
    vendorCaterer: 'user-vendor-caterer',
    vendorPhoto: 'user-vendor-photo',
    vendorFlorist: 'user-vendor-florist',
    vendorMusic: 'user-vendor-music',
    vendorBakery: 'user-vendor-bakery',
    vendorTravel: 'user-vendor-travel',
    vendorVideo: 'user-vendor-video',
    vendorOfficiant: 'user-vendor-officiant',
  },
  vendors: {
    oaks: 'vendor-austin-oaks',
    harvest: 'vendor-harvest-table',
    lens: 'vendor-true-lens',
    petal: 'vendor-petal-and-stem',
    groove: 'vendor-sunset-groove',
    sugar: 'vendor-sugar-house',
    transfer: 'vendor-skyline-transfers',
    film: 'vendor-ember-films',
    vows: 'vendor-open-vows',
  },
  weddings: {
    alexJordan: 'wedding-alex-jordan',
    samRiley: 'wedding-sam-riley',
  },
  guests: {
    g1: 'guest-morgan-lee',
    g2: 'guest-priya-shah',
    g3: 'guest-chris-nguyen',
    g4: 'guest-elena-ruiz',
    g5: 'guest-ben-carter',
    g6: 'guest-aisha-khan',
    g7: 'guest-owen-park',
    g8: 'guest-grace-kim',
  },
  conversations: {
    venue: 'conversation-aj-oaks',
    florist: 'conversation-aj-petal',
    photo: 'conversation-aj-lens',
    caterer: 'conversation-aj-harvest',
    declinedMusic: 'conversation-aj-groove-declined',
  },
  messages: {
    venueInquiry: 'message-venue-inquiry',
    venueAvailability: 'message-venue-availability',
    venueQuoteReq: 'message-venue-quote-req',
    venueQuote: 'message-venue-quote',
    venueClarify: 'message-venue-clarify',
    venueBookReq: 'message-venue-book-req',
    venueBookConfirm: 'message-venue-book-confirm',
    venueSystem: 'message-venue-system',
    floristInquiry: 'message-florist-inquiry',
    floristQuote: 'message-florist-quote',
    floristRevision: 'message-florist-revision',
    photoInquiry: 'message-photo-inquiry',
    photoQuote: 'message-photo-quote',
    musicInquiry: 'message-music-inquiry',
    musicDecline: 'message-music-decline',
    catererInquiry: 'message-caterer-inquiry',
    catererAvail: 'message-caterer-avail',
  },
  payments: {
    venueDebt: 'payment-venue-debt',
    venueDeposit: 'payment-venue-deposit',
    venueFee: 'payment-venue-fee',
    venuePayout: 'payment-venue-payout',
    floristDebt: 'payment-florist-debt',
    floristDeposit: 'payment-florist-deposit',
    photoDebt: 'payment-photo-debt',
    photoRefundDraft: 'payment-photo-refund-draft',
  },
} as const

/** Media — upload metadata only; attach real files at seed time. */
export const sampleMedia = [
  {
    id: sampleIds.media.avatarAlex,
    alt: 'Alex Rivera profile photo',
    filename: 'alex-rivera-avatar.jpg',
  },
  {
    id: sampleIds.media.avatarJordan,
    alt: 'Jordan Blake profile photo',
    filename: 'jordan-blake-avatar.jpg',
  },
  {
    id: sampleIds.media.avatarMaya,
    alt: 'Maya Chen, Austin Oaks Events owner',
    filename: 'maya-chen-avatar.jpg',
  },
  {
    id: sampleIds.media.venueHero,
    alt: 'Austin Oaks ceremony lawn at golden hour',
    filename: 'austin-oaks-hero.jpg',
  },
  {
    id: sampleIds.media.venueGallery1,
    alt: 'Reception pavilion strung with lights',
    filename: 'austin-oaks-pavilion.jpg',
  },
  {
    id: sampleIds.media.venueGallery2,
    alt: 'Indoor ballroom set for dinner',
    filename: 'austin-oaks-ballroom.jpg',
  },
  {
    id: sampleIds.media.floristHero,
    alt: 'Seasonal bouquet with peach garden roses',
    filename: 'petal-stem-hero.jpg',
  },
  {
    id: sampleIds.media.photoHero,
    alt: 'Couple portrait under live oak canopy',
    filename: 'true-lens-hero.jpg',
  },
  {
    id: sampleIds.media.catererHero,
    alt: 'Family-style harvest dinner platters',
    filename: 'harvest-table-hero.jpg',
  },
  {
    id: sampleIds.media.musicHero,
    alt: 'DJ booth with warm stage wash',
    filename: 'sunset-groove-hero.jpg',
  },
  {
    id: sampleIds.media.bakeryHero,
    alt: 'Three-tier buttercream wedding cake',
    filename: 'sugar-house-hero.jpg',
  },
  {
    id: sampleIds.media.quotePdf,
    alt: 'Austin Oaks venue quote PDF',
    filename: 'austin-oaks-quote.pdf',
  },
]

/** Users — couples, vendors, and admin. Password is for local seed only. */
export const sampleUsers = [
  {
    id: sampleIds.users.admin,
    email: 'admin@marrymap.test',
    password: 'SeedAdmin!23',
    role: 'admin',
    displayName: 'Marrymap Admin',
    phone: '+1-512-555-0100',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: false,
      percentComplete: 100,
    },
  },
  {
    id: sampleIds.users.coupleAlex,
    email: 'alex.rivera@example.com',
    password: 'SeedCouple!23',
    role: 'couple',
    displayName: 'Alex Rivera',
    phone: '+1-512-555-0142',
    avatar: sampleIds.media.avatarAlex,
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: true,
      vendorProfileLinked: false,
      percentComplete: 100,
    },
    coupleProfile: {
      partnerOneName: 'Alex Rivera',
      partnerTwoName: 'Jordan Blake',
      engagementDate: '2025-11-08',
      preferredStyle: ['garden', 'modern'],
      homeArea: {
        city: 'Austin',
        region: 'TX',
        postalCode: '78704',
        country: 'US',
      },
      referralCode: 'ALEX-GARDEN-27',
    },
    coupleBalances: {
      stripeCustomerId: 'cus_sample_alex',
      totalDebt: 18500,
      totalPaid: 4500,
      outstandingBalance: 14000,
    },
    savedWeddings: [sampleIds.weddings.alexJordan],
    planTier: 'straightforward',
  },
  {
    id: sampleIds.users.coupleJordan,
    email: 'jordan.blake@example.com',
    password: 'SeedCouple!23',
    role: 'couple',
    displayName: 'Jordan Blake',
    phone: '+1-512-555-0143',
    avatar: sampleIds.media.avatarJordan,
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: true,
      vendorProfileLinked: false,
      percentComplete: 90,
    },
    coupleProfile: {
      partnerOneName: 'Alex Rivera',
      partnerTwoName: 'Jordan Blake',
      engagementDate: '2025-11-08',
      preferredStyle: ['garden', 'classic'],
      homeArea: {
        city: 'Austin',
        region: 'TX',
        postalCode: '78745',
        country: 'US',
      },
      referralCode: 'JORDAN-OAK-27',
      referredBy: sampleIds.users.coupleAlex,
    },
    coupleBalances: {
      stripeCustomerId: 'cus_sample_jordan',
      totalDebt: 18500,
      totalPaid: 4500,
      outstandingBalance: 14000,
    },
    savedWeddings: [sampleIds.weddings.alexJordan],
    planTier: 'straightforward',
  },
  {
    id: sampleIds.users.coupleSam,
    email: 'sam.ortiz@example.com',
    password: 'SeedCouple!23',
    role: 'couple',
    displayName: 'Sam Ortiz',
    phone: '+1-737-555-0190',
    onboardingStatus: 'in_progress',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: false,
      firstWeddingCreated: true,
      vendorProfileLinked: false,
      percentComplete: 55,
    },
    coupleProfile: {
      partnerOneName: 'Sam Ortiz',
      partnerTwoName: 'Riley Chen',
      engagementDate: '2026-02-14',
      preferredStyle: ['rustic', 'destination'],
      homeArea: {
        city: 'Round Rock',
        region: 'TX',
        postalCode: '78664',
        country: 'US',
      },
      referralCode: 'SAM-RUSTIC-28',
      referredBy: sampleIds.users.coupleAlex,
    },
    coupleBalances: {
      totalDebt: 0,
      totalPaid: 0,
      outstandingBalance: 0,
    },
    savedWeddings: [sampleIds.weddings.samRiley],
    planTier: 'none',
  },
  {
    id: sampleIds.users.coupleRiley,
    email: 'riley.chen@example.com',
    password: 'SeedCouple!23',
    role: 'couple',
    displayName: 'Riley Chen',
    onboardingStatus: 'not_started',
    accountProgress: {
      profileComplete: false,
      preferencesComplete: false,
      firstWeddingCreated: false,
      vendorProfileLinked: false,
      percentComplete: 10,
    },
    coupleProfile: {
      partnerOneName: 'Sam Ortiz',
      partnerTwoName: 'Riley Chen',
      preferredStyle: ['minimal'],
      homeArea: {
        city: 'Austin',
        region: 'TX',
        country: 'US',
      },
      referralCode: 'RILEY-MIN-28',
    },
    planTier: 'none',
  },
  {
    id: sampleIds.users.vendorVenue,
    email: 'maya@austinoaks.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Maya Chen',
    phone: '+1-512-555-0201',
    avatar: sampleIds.media.avatarMaya,
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.oaks,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorCaterer,
    email: 'luis@harvesttable.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Luis Mendoza',
    phone: '+1-512-555-0202',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.harvest,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorPhoto,
    email: 'nina@truelens.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Nina Park',
    phone: '+1-512-555-0203',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.lens,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorFlorist,
    email: 'hana@petalandstem.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Hana Brooks',
    phone: '+1-512-555-0204',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 95,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.petal,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorMusic,
    email: 'devon@sunsetgroove.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Devon Walsh',
    phone: '+1-512-555-0205',
    onboardingStatus: 'in_progress',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: false,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 70,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.groove,
      businessRole: 'manager',
    },
  },
  {
    id: sampleIds.users.vendorBakery,
    email: 'claire@sugarhouse.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Claire Nguyen',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.sugar,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorTravel,
    email: 'omar@skylinetransfers.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Omar Hassan',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.transfer,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorVideo,
    email: 'tess@emberfilms.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Tess Alvarez',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.film,
      businessRole: 'owner',
    },
  },
  {
    id: sampleIds.users.vendorOfficiant,
    email: 'rev.patel@openvows.example',
    password: 'SeedVendor!23',
    role: 'vendor',
    displayName: 'Rev. Anika Patel',
    onboardingStatus: 'complete',
    accountProgress: {
      profileComplete: true,
      preferencesComplete: true,
      firstWeddingCreated: false,
      vendorProfileLinked: true,
      percentComplete: 100,
    },
    vendorAccount: {
      vendorListing: sampleIds.vendors.vows,
      businessRole: 'owner',
    },
  },
]

/** Vendors — one listing per marketplace category. */
export const sampleVendors = [
  {
    id: sampleIds.vendors.oaks,
    _status: 'published',
    schemaOrgType: 'EventVenue',
    name: 'Austin Oaks Estate',
    slug: 'austin-oaks-estate',
    category: 'venue',
    description:
      'Hill Country estate with oak-shaded ceremony lawn, pavilion reception, and indoor ballroom backup.',
    url: 'https://austinoaks.example',
    image: sampleIds.media.venueHero,
    gallery: [
      { image: sampleIds.media.venueGallery1, caption: 'Pavilion under string lights' },
      { image: sampleIds.media.venueGallery2, caption: 'Ballroom dinner setup' },
    ],
    owner: sampleIds.users.vendorVenue,
    contactPoint: {
      email: 'bookings@austinoaks.example',
      telephone: '+1-512-555-1100',
      contactType: 'customer service',
    },
    address: {
      streetAddress: '8800 Old Bee Cave Rd',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78736',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2421, longitude: -97.8124 },
    areaServed: [
      { label: 'Greater Austin', city: 'Austin', region: 'TX', radiusMiles: 40 },
    ],
    serviceAreaSummary: 'Greater Austin, 40 mi',
    priceRange: '$$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 8000,
      maxPrice: 18000,
      unitText: 'wedding',
    },
    capacity: {
      maximumAttendeeCapacity: 220,
      minimumAttendeeCapacity: 60,
    },
    services: [
      {
        name: 'Ceremony + reception site',
        serviceType: 'Venue rental',
        description: '10-hour exclusive use, ceremony lawn, pavilion, bridal suite.',
        offers: { price: 12000, priceCurrency: 'USD', availability: 'InStock' },
      },
      {
        name: 'Rehearsal add-on',
        serviceType: 'Venue rental',
        description: '2-hour rehearsal the evening before.',
        offers: { price: 750, priceCurrency: 'USD', availability: 'LimitedAvailability' },
      },
    ],
    aggregateRating: {
      ratingValue: 4.8,
      reviewCount: 126,
      bestRating: 5,
      worstRating: 1,
    },
    sameAs: [
      { url: 'https://instagram.com/austinoaks.example' },
      { url: 'https://maps.example/austinoaks' },
    ],
    amenities: [
      { name: 'On-site parking', value: true },
      { name: 'Bridal suite', value: true },
      { name: 'Rain backup', value: true },
      { name: 'In-house catering required', value: false },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_oaks',
      chargesEnabled: true,
      payoutsEnabled: true,
      currentMonthGross: 12000,
      currentMonthNet: 10800,
      currentMonthOutstanding: 9000,
      lifetimeGross: 240000,
      lifetimeCollected: 210000,
      monthlyBillings: [
        {
          period: '2026-07',
          grossBillings: 12000,
          platformFees: 1200,
          netBillings: 10800,
          amountCollected: 3000,
          amountOutstanding: 9000,
          paymentCount: 1,
        },
      ],
    },
  },
  {
    id: sampleIds.vendors.harvest,
    _status: 'published',
    schemaOrgType: 'FoodEstablishment',
    name: 'Harvest Table Catering',
    slug: 'harvest-table-catering',
    category: 'caterer',
    description: 'Seasonal Texas menus, family-style or plated, full bar packages available.',
    url: 'https://harvesttable.example',
    image: sampleIds.media.catererHero,
    owner: sampleIds.users.vendorCaterer,
    contactPoint: {
      email: 'hello@harvesttable.example',
      telephone: '+1-512-555-1200',
      contactType: 'sales',
    },
    address: {
      streetAddress: '2100 S Lamar Blvd',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78704',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2489, longitude: -97.7684 },
    areaServed: [
      { label: 'Austin metro', city: 'Austin', region: 'TX', radiusMiles: 60 },
    ],
    serviceAreaSummary: 'Austin metro, 60 mi',
    priceRange: '$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 75,
      maxPrice: 145,
      unitText: 'guest',
    },
    services: [
      {
        name: 'Plated dinner',
        serviceType: 'Catering',
        description: 'Three-course plated service including china and staffing.',
        offers: { price: 110, priceCurrency: 'USD', availability: 'InStock' },
      },
      {
        name: 'Open bar (5 hours)',
        serviceType: 'Beverage',
        description: 'Beer, wine, and signature cocktails.',
        offers: { price: 45, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.6, reviewCount: 88, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://instagram.com/harvesttable.example' }],
    amenities: [
      { name: 'Tastings included', value: true },
      { name: 'Dietary accommodations', value: true },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_harvest',
      chargesEnabled: true,
      payoutsEnabled: true,
      currentMonthGross: 0,
      currentMonthNet: 0,
      currentMonthOutstanding: 0,
      lifetimeGross: 98000,
      lifetimeCollected: 92000,
      monthlyBillings: [],
    },
  },
  {
    id: sampleIds.vendors.lens,
    _status: 'published',
    schemaOrgType: 'ProfessionalService',
    name: 'True Lens Studio',
    slug: 'true-lens-studio',
    category: 'photographer',
    description: 'Documentary wedding photography with an editorial second shooter.',
    url: 'https://truelens.example',
    image: sampleIds.media.photoHero,
    owner: sampleIds.users.vendorPhoto,
    contactPoint: {
      email: 'book@truelens.example',
      telephone: '+1-512-555-1300',
      contactType: 'customer service',
    },
    address: {
      streetAddress: '401 Congress Ave',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78701',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2669, longitude: -97.7428 },
    areaServed: [
      { label: 'Central Texas', region: 'TX', radiusMiles: 120 },
      { label: 'Destination (travel fee)', radiusMiles: 0 },
    ],
    serviceAreaSummary: 'Central Texas + destination',
    priceRange: '$$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 3200,
      maxPrice: 7800,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Full-day coverage',
        serviceType: 'Photography',
        description: '10 hours, two photographers, online gallery, print rights.',
        offers: { price: 5200, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.9, reviewCount: 214, bestRating: 5, worstRating: 1 },
    sameAs: [
      { url: 'https://instagram.com/truelens.example' },
      { url: 'https://truelens.example/portfolio' },
    ],
    amenities: [
      { name: 'Engagement session', value: true },
      { name: 'Album design', value: true },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_lens',
      chargesEnabled: true,
      payoutsEnabled: false,
      currentMonthGross: 5200,
      currentMonthNet: 4680,
      currentMonthOutstanding: 5200,
      lifetimeGross: 156000,
      lifetimeCollected: 140000,
      monthlyBillings: [
        {
          period: '2026-07',
          grossBillings: 5200,
          platformFees: 520,
          netBillings: 4680,
          amountCollected: 0,
          amountOutstanding: 5200,
          paymentCount: 1,
        },
      ],
    },
  },
  {
    id: sampleIds.vendors.petal,
    _status: 'published',
    schemaOrgType: 'Florist',
    name: 'Petal & Stem',
    slug: 'petal-and-stem',
    category: 'florist',
    description: 'Garden-forward florals with locally grown stems and sustainable foam-free design.',
    url: 'https://petalandstem.example',
    image: sampleIds.media.floristHero,
    owner: sampleIds.users.vendorFlorist,
    contactPoint: {
      email: 'studio@petalandstem.example',
      telephone: '+1-512-555-1400',
      contactType: 'customer service',
    },
    address: {
      streetAddress: '1406 S Congress Ave',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78704',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2495, longitude: -97.7498 },
    areaServed: [{ label: 'Austin', city: 'Austin', region: 'TX', radiusMiles: 45 }],
    serviceAreaSummary: 'Austin, 45 mi',
    priceRange: '$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 1800,
      maxPrice: 6500,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Ceremony + reception package',
        serviceType: 'Floral design',
        description: 'Arch, bouquets, boutonnières, 10 centerpieces, delivery/setup.',
        offers: { price: 3800, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.7, reviewCount: 67, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://instagram.com/petalandstem.example' }],
    amenities: [
      { name: 'Foam-free designs', value: true },
      { name: 'Same-week rush', value: false },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_petal',
      chargesEnabled: true,
      payoutsEnabled: true,
      currentMonthGross: 3500,
      currentMonthNet: 3150,
      currentMonthOutstanding: 2000,
      lifetimeGross: 72000,
      lifetimeCollected: 65000,
      monthlyBillings: [
        {
          period: '2026-07',
          grossBillings: 3500,
          platformFees: 350,
          netBillings: 3150,
          amountCollected: 1500,
          amountOutstanding: 2000,
          paymentCount: 1,
        },
      ],
    },
  },
  {
    id: sampleIds.vendors.groove,
    _status: 'published',
    schemaOrgType: 'EntertainmentBusiness',
    name: 'Sunset Groove DJ',
    slug: 'sunset-groove-dj',
    category: 'music',
    description: 'Wedding DJ with ceremony mics, reception lighting, and bilingual MC.',
    url: 'https://sunsetgroove.example',
    image: sampleIds.media.musicHero,
    owner: sampleIds.users.vendorMusic,
    contactPoint: {
      email: 'book@sunsetgroove.example',
      telephone: '+1-512-555-1500',
      contactType: 'customer service',
    },
    address: {
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78702',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2605, longitude: -97.725 },
    areaServed: [{ label: 'Central Texas', region: 'TX', radiusMiles: 90 }],
    serviceAreaSummary: 'Central Texas, 90 mi',
    priceRange: '$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 1400,
      maxPrice: 3200,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Ceremony + reception DJ',
        serviceType: 'Entertainment',
        description: '6 hours, wireless mics, uplighting package.',
        offers: { price: 2200, priceCurrency: 'USD', availability: 'LimitedAvailability' },
      },
    ],
    aggregateRating: { ratingValue: 4.5, reviewCount: 41, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://instagram.com/sunsetgroove.example' }],
    amenities: [
      { name: 'Uplighting included', value: true },
      { name: 'Live sax add-on', value: true },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_groove',
      chargesEnabled: true,
      payoutsEnabled: true,
      lifetimeGross: 41000,
      lifetimeCollected: 39000,
      monthlyBillings: [],
    },
  },
  {
    id: sampleIds.vendors.sugar,
    _status: 'published',
    schemaOrgType: 'Bakery',
    name: 'Sugar House Bakery',
    slug: 'sugar-house-bakery',
    category: 'bakery',
    description: 'Custom buttercream and semi-naked cakes, dessert tables, gluten-free options.',
    url: 'https://sugarhouse.example',
    image: sampleIds.media.bakeryHero,
    owner: sampleIds.users.vendorBakery,
    contactPoint: {
      email: 'orders@sugarhouse.example',
      telephone: '+1-512-555-1600',
      contactType: 'orders',
    },
    address: {
      streetAddress: '500 W Mary St',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78704',
      addressCountry: 'US',
    },
    geo: { latitude: 30.2458, longitude: -97.7661 },
    areaServed: [{ label: 'Austin', city: 'Austin', region: 'TX', radiusMiles: 35 }],
    serviceAreaSummary: 'Austin, 35 mi',
    priceRange: '$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 450,
      maxPrice: 1800,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Three-tier cake',
        serviceType: 'Bakery',
        description: 'Serves ~100, tasting included, delivery within Austin.',
        offers: { price: 850, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.8, reviewCount: 93, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://instagram.com/sugarhouse.example' }],
    amenities: [
      { name: 'Tasting appointment', value: true },
      { name: 'Gluten-free tiers', value: true },
    ],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_sugar',
      chargesEnabled: false,
      payoutsEnabled: false,
      lifetimeGross: 18000,
      lifetimeCollected: 16000,
      monthlyBillings: [],
    },
  },
  {
    id: sampleIds.vendors.transfer,
    _status: 'published',
    schemaOrgType: 'TravelAgency',
    name: 'Skyline Transfers',
    slug: 'skyline-transfers',
    category: 'travel',
    description: 'Guest airport shuttles and hotel-to-venue coach service for wedding weekends.',
    url: 'https://skylinetransfers.example',
    owner: sampleIds.users.vendorTravel,
    contactPoint: {
      email: 'dispatch@skylinetransfers.example',
      telephone: '+1-512-555-1700',
      contactType: 'dispatch',
    },
    address: {
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78719',
      addressCountry: 'US',
    },
    geo: { latitude: 30.1975, longitude: -97.6664 },
    areaServed: [{ label: 'AUS airport corridor', city: 'Austin', region: 'TX', radiusMiles: 50 }],
    serviceAreaSummary: 'AUS + hotel corridor',
    priceRange: '$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 800,
      maxPrice: 3500,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Guest shuttle loop',
        serviceType: 'Ground transport',
        description: 'Two coach runs hotel ↔ venue, up to 55 seats.',
        offers: { price: 1600, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.4, reviewCount: 29, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://skylinetransfers.example' }],
    amenities: [{ name: 'ADA coach available', value: true }],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_transfer',
      chargesEnabled: true,
      payoutsEnabled: true,
      lifetimeGross: 22000,
      lifetimeCollected: 20000,
      monthlyBillings: [],
    },
  },
  {
    id: sampleIds.vendors.film,
    _status: 'draft',
    schemaOrgType: 'ProfessionalService',
    name: 'Ember Films',
    slug: 'ember-films',
    category: 'videographer',
    description: 'Cinematic highlight films and full-ceremony documentation.',
    url: 'https://emberfilms.example',
    owner: sampleIds.users.vendorVideo,
    contactPoint: {
      email: 'hello@emberfilms.example',
      telephone: '+1-512-555-1800',
      contactType: 'customer service',
    },
    address: {
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78751',
      addressCountry: 'US',
    },
    geo: { latitude: 30.311, longitude: -97.722 },
    areaServed: [{ label: 'Texas', region: 'TX', radiusMiles: 200 }],
    serviceAreaSummary: 'Texas-wide',
    priceRange: '$$$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 2800,
      maxPrice: 7000,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Highlight + ceremony',
        serviceType: 'Videography',
        description: '8 hours, two shooters, 5–7 min highlight, ceremony edit.',
        offers: { price: 4500, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 4.9, reviewCount: 52, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://vimeo.com/emberfilms.example' }],
    amenities: [{ name: 'Drone add-on', value: true }],
    isActive: false,
    billing: {
      stripeConnectAccountId: 'acct_sample_film',
      chargesEnabled: false,
      payoutsEnabled: false,
      lifetimeGross: 0,
      lifetimeCollected: 0,
      monthlyBillings: [],
    },
  },
  {
    id: sampleIds.vendors.vows,
    _status: 'published',
    schemaOrgType: 'ProfessionalService',
    name: 'Open Vows Officiant',
    slug: 'open-vows-officiant',
    category: 'officiant',
    description: 'Custom ceremonies — interfaith, secular, and bilingual options.',
    url: 'https://openvows.example',
    owner: sampleIds.users.vendorOfficiant,
    contactPoint: {
      email: 'rev.patel@openvows.example',
      telephone: '+1-512-555-1900',
      contactType: 'customer service',
    },
    address: {
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78703',
      addressCountry: 'US',
    },
    geo: { latitude: 30.284, longitude: -97.76 },
    areaServed: [{ label: 'Greater Austin', city: 'Austin', region: 'TX', radiusMiles: 50 }],
    serviceAreaSummary: 'Greater Austin, 50 mi',
    priceRange: '$',
    typicalPrice: {
      currency: 'USD',
      minPrice: 350,
      maxPrice: 900,
      unitText: 'wedding',
    },
    services: [
      {
        name: 'Custom ceremony',
        serviceType: 'Officiant',
        description: 'Planning call, script draft, rehearsal optional, day-of ceremony.',
        offers: { price: 550, priceCurrency: 'USD', availability: 'InStock' },
      },
    ],
    aggregateRating: { ratingValue: 5, reviewCount: 38, bestRating: 5, worstRating: 1 },
    sameAs: [{ url: 'https://openvows.example' }],
    amenities: [{ name: 'Bilingual English/Spanish', value: true }],
    isActive: true,
    billing: {
      stripeConnectAccountId: 'acct_sample_vows',
      chargesEnabled: true,
      payoutsEnabled: true,
      lifetimeGross: 12000,
      lifetimeCollected: 11000,
      monthlyBillings: [],
    },
  },
]

/** Weddings — active planning + early intake. */
export const sampleWeddings = [
  {
    id: sampleIds.weddings.alexJordan,
    title: 'Alex & Jordan — Fall 2027',
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    status: 'planning',
    weddingDate: '2027-10-16',
    guestCount: 140,
    description:
      'Garden ceremony under live oaks, modern reception dinner, warm peach and sage palette.',
    generalArea: {
      city: 'Austin',
      region: 'TX',
      postalCode: '78736',
      country: 'US',
      radiusMiles: 40,
    },
    budget: { currency: 'USD', min: 35000, max: 55000 },
    budgetTotal: 55000,
    totalCost: 20700,
    paymentTotals: {
      totalDebt: 20700,
      totalPaid: 4500,
      outstandingBalance: 16200,
    },
    selectedVendors: [
      {
        category: 'venue',
        vendor: sampleIds.vendors.oaks,
        conversation: sampleIds.conversations.venue,
        quotedPrice: 12000,
        acceptedPrice: 12000,
        priceFlag: 'within_range',
        selectionStatus: 'booked',
      },
      {
        category: 'florist',
        vendor: sampleIds.vendors.petal,
        conversation: sampleIds.conversations.florist,
        quotedPrice: 3800,
        acceptedPrice: 3500,
        priceFlag: 'within_range',
        selectionStatus: 'booked',
      },
      {
        category: 'photographer',
        vendor: sampleIds.vendors.lens,
        conversation: sampleIds.conversations.photo,
        quotedPrice: 5200,
        priceFlag: 'within_range',
        selectionStatus: 'quote_received',
      },
      {
        category: 'caterer',
        vendor: sampleIds.vendors.harvest,
        conversation: sampleIds.conversations.caterer,
        quotedPrice: 15400,
        priceFlag: 'over_budget',
        selectionStatus: 'inquiry_sent',
      },
      {
        category: 'music',
        vendor: sampleIds.vendors.groove,
        conversation: sampleIds.conversations.declinedMusic,
        quotedPrice: 2200,
        priceFlag: 'within_range',
        selectionStatus: 'rejected',
      },
      {
        category: 'bakery',
        vendor: sampleIds.vendors.sugar,
        quotedPrice: 850,
        priceFlag: 'within_range',
        selectionStatus: 'shortlisted',
      },
    ],
    packageOptions: [
      {
        name: 'Garden Classic',
        summary: 'Estate venue, seasonal florals, documentary photo, plated dinner.',
        estimatedTotal: 41200,
        vendors: [
          sampleIds.vendors.oaks,
          sampleIds.vendors.petal,
          sampleIds.vendors.lens,
          sampleIds.vendors.harvest,
          sampleIds.vendors.sugar,
        ],
        isSelected: true,
      },
      {
        name: 'Lean Celebration',
        summary: 'Same venue with leaner florist and DJ entertainment swap.',
        estimatedTotal: 36800,
        vendors: [
          sampleIds.vendors.oaks,
          sampleIds.vendors.petal,
          sampleIds.vendors.lens,
          sampleIds.vendors.groove,
          sampleIds.vendors.sugar,
        ],
        isSelected: false,
      },
    ],
    timeline: [
      {
        weekOf: '2026-07-20',
        title: 'Lock venue contract',
        description: 'Sign venue agreement and schedule deposit.',
        status: 'done',
        relatedCategory: 'venue',
      },
      {
        weekOf: '2026-08-03',
        title: 'Finalize florist scope',
        description: 'Confirm arch + centerpiece counts after guest estimate.',
        status: 'in_progress',
        relatedCategory: 'florist',
      },
      {
        weekOf: '2026-08-17',
        title: 'Book photographer',
        description: 'Accept True Lens quote or request revision.',
        status: 'upcoming',
        relatedCategory: 'photographer',
      },
      {
        weekOf: '2026-09-07',
        title: 'Catering tasting',
        description: 'Sample plated menus and bar package.',
        status: 'upcoming',
        relatedCategory: 'caterer',
      },
      {
        weekOf: '2027-09-27',
        title: 'Final headcount',
        description: 'Send final guest count to venue and caterer.',
        status: 'upcoming',
        relatedCategory: 'venue',
      },
    ],
    guestList: [
      sampleIds.guests.g1,
      sampleIds.guests.g2,
      sampleIds.guests.g3,
      sampleIds.guests.g4,
      sampleIds.guests.g5,
      sampleIds.guests.g6,
    ],
  },
  {
    id: sampleIds.weddings.samRiley,
    title: 'Sam & Riley — Spring 2028',
    couple: [sampleIds.users.coupleSam],
    status: 'intake',
    weddingDate: '2028-04-22',
    guestCount: 90,
    description: 'Rustic-leaning day with destination feel; still gathering preferences.',
    generalArea: {
      city: 'Dripping Springs',
      region: 'TX',
      postalCode: '78620',
      country: 'US',
      radiusMiles: 55,
    },
    budget: { currency: 'USD', min: 22000, max: 38000 },
    budgetTotal: 38000,
    totalCost: 0,
    paymentTotals: {
      totalDebt: 0,
      totalPaid: 0,
      outstandingBalance: 0,
    },
    selectedVendors: [
      {
        category: 'travel',
        vendor: sampleIds.vendors.transfer,
        priceFlag: 'within_range',
        selectionStatus: 'shortlisted',
      },
      {
        category: 'officiant',
        vendor: sampleIds.vendors.vows,
        priceFlag: 'within_range',
        selectionStatus: 'shortlisted',
      },
    ],
    packageOptions: [],
    timeline: [
      {
        weekOf: '2026-08-01',
        title: 'Complete intake questionnaire',
        description: 'Style, guest estimate, and must-have vendors.',
        status: 'in_progress',
      },
    ],
    guestList: [sampleIds.guests.g7, sampleIds.guests.g8],
  },
]

/** Guests — RSVP variety across both weddings. */
export const sampleGuests = [
  {
    id: sampleIds.guests.g1,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Morgan Lee',
    email: 'morgan.lee@example.com',
    phone: '+1-415-555-2001',
    side: 'partner_one',
    partySize: 2,
    plusOneAllowed: true,
    plusOneName: 'Casey Lee',
    rsvpStatus: 'accepted',
    mealChoice: 'Herb chicken',
    dietaryRestrictions: 'None',
    household: 'Lee',
    address: {
      streetAddress: '88 Valencia St',
      addressLocality: 'San Francisco',
      addressRegion: 'CA',
      postalCode: '94103',
      addressCountry: 'US',
    },
    notes: 'College roommate of Alex.',
    tags: ['vip', 'wedding_party'],
  },
  {
    id: sampleIds.guests.g2,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Priya Shah',
    email: 'priya.shah@example.com',
    side: 'partner_two',
    partySize: 1,
    plusOneAllowed: false,
    rsvpStatus: 'accepted',
    mealChoice: 'Vegetarian risotto',
    dietaryRestrictions: 'Vegetarian; no nuts',
    household: 'Shah',
    address: {
      streetAddress: '1200 Barton Springs Rd',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78704',
      addressCountry: 'US',
    },
    tags: ['family'],
  },
  {
    id: sampleIds.guests.g3,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Chris Nguyen',
    email: 'chris.nguyen@example.com',
    phone: '+1-512-555-2003',
    side: 'both',
    partySize: 3,
    plusOneAllowed: true,
    plusOneName: 'Taylor Nguyen',
    rsvpStatus: 'invited',
    household: 'Nguyen',
    address: {
      streetAddress: '44 Rainey St',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78701',
      addressCountry: 'US',
    },
    notes: 'Bringing child; needs high chair.',
    tags: ['family', 'child'],
  },
  {
    id: sampleIds.guests.g4,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Elena Ruiz',
    email: 'elena.ruiz@example.com',
    side: 'partner_one',
    partySize: 1,
    rsvpStatus: 'maybe',
    dietaryRestrictions: 'Gluten-free',
    household: 'Ruiz',
    address: {
      addressLocality: 'Dallas',
      addressRegion: 'TX',
      postalCode: '75201',
      addressCountry: 'US',
    },
    tags: ['vip'],
  },
  {
    id: sampleIds.guests.g5,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Ben Carter',
    email: 'ben.carter@example.com',
    side: 'partner_two',
    partySize: 2,
    plusOneAllowed: true,
    rsvpStatus: 'declined',
    household: 'Carter',
    notes: 'Travel conflict; sending gift.',
    tags: [],
  },
  {
    id: sampleIds.guests.g6,
    wedding: sampleIds.weddings.alexJordan,
    fullName: 'Aisha Khan',
    email: 'aisha.khan@example.com',
    phone: '+1-737-555-2006',
    side: 'other',
    partySize: 1,
    rsvpStatus: 'pending',
    household: 'Khan',
    address: {
      streetAddress: '900 E 5th St',
      addressLocality: 'Austin',
      addressRegion: 'TX',
      postalCode: '78702',
      addressCountry: 'US',
    },
    tags: ['accessibility'],
    notes: 'Wheelchair access for seating.',
  },
  {
    id: sampleIds.guests.g7,
    wedding: sampleIds.weddings.samRiley,
    fullName: 'Owen Park',
    email: 'owen.park@example.com',
    side: 'partner_one',
    partySize: 1,
    rsvpStatus: 'pending',
    household: 'Park',
    tags: ['family'],
  },
  {
    id: sampleIds.guests.g8,
    wedding: sampleIds.weddings.samRiley,
    fullName: 'Grace Kim',
    email: 'grace.kim@example.com',
    side: 'partner_two',
    partySize: 2,
    plusOneAllowed: true,
    rsvpStatus: 'invited',
    household: 'Kim',
    tags: ['wedding_party'],
  },
]

/** Conversations — threads at different protocol stages. */
export const sampleConversations = [
  {
    id: sampleIds.conversations.venue,
    subject: 'Booking confirmation — Venue',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.oaks,
    category: 'venue',
    status: 'booked',
    participants: [
      sampleIds.users.coupleAlex,
      sampleIds.users.coupleJordan,
      sampleIds.users.vendorVenue,
    ],
    openedBy: sampleIds.users.coupleAlex,
    activeQuote: {
      currency: 'USD',
      total: 12000,
      validUntil: '2026-08-01',
      priceFlag: 'within_range',
    },
    lastMessageAt: '2026-07-18T16:40:00.000Z',
    lastMessageType: 'booking_confirmation',
    unreadByCouple: 0,
    unreadByVendor: 0,
  },
  {
    id: sampleIds.conversations.florist,
    subject: 'Quote revision — Florist',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.petal,
    category: 'florist',
    status: 'booked',
    participants: [sampleIds.users.coupleAlex, sampleIds.users.vendorFlorist],
    openedBy: sampleIds.users.coupleAlex,
    activeQuote: {
      currency: 'USD',
      total: 3500,
      validUntil: '2026-08-15',
      priceFlag: 'within_range',
    },
    lastMessageAt: '2026-07-19T14:05:00.000Z',
    lastMessageType: 'booking_confirmation',
    unreadByCouple: 0,
    unreadByVendor: 1,
  },
  {
    id: sampleIds.conversations.photo,
    subject: 'Quote response — Photographer',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.lens,
    category: 'photographer',
    status: 'quoted',
    participants: [
      sampleIds.users.coupleAlex,
      sampleIds.users.coupleJordan,
      sampleIds.users.vendorPhoto,
    ],
    openedBy: sampleIds.users.coupleJordan,
    activeQuote: {
      currency: 'USD',
      total: 5200,
      validUntil: '2026-09-01',
      priceFlag: 'within_range',
    },
    lastMessageAt: '2026-07-20T11:20:00.000Z',
    lastMessageType: 'quote_response',
    unreadByCouple: 1,
    unreadByVendor: 0,
  },
  {
    id: sampleIds.conversations.caterer,
    subject: 'Availability check — Caterer',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.harvest,
    category: 'caterer',
    status: 'awaiting_vendor',
    participants: [sampleIds.users.coupleAlex, sampleIds.users.vendorCaterer],
    openedBy: sampleIds.users.coupleAlex,
    activeQuote: {
      currency: 'USD',
      priceFlag: 'over_budget',
    },
    lastMessageAt: '2026-07-21T09:15:00.000Z',
    lastMessageType: 'availability_check',
    unreadByCouple: 0,
    unreadByVendor: 2,
  },
  {
    id: sampleIds.conversations.declinedMusic,
    subject: 'Decline — Music',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.groove,
    category: 'music',
    status: 'declined',
    participants: [sampleIds.users.coupleAlex, sampleIds.users.vendorMusic],
    openedBy: sampleIds.users.coupleAlex,
    lastMessageAt: '2026-07-15T18:00:00.000Z',
    lastMessageType: 'decline',
    unreadByCouple: 0,
    unreadByVendor: 0,
  },
]

/** Messages — covers the communication scheme types. */
export const sampleMessages = [
  {
    id: sampleIds.messages.venueInquiry,
    conversation: sampleIds.conversations.venue,
    type: 'inquiry',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'We love the oak lawn — are you open for mid-October 2027?',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Ceremony lawn + pavilion reception, 10-hour exclusive use.',
        budgetAllocation: 13000,
        styleNotes: 'Garden ceremony, modern reception, peach and sage palette.',
      },
    },
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorVenue],
  },
  {
    id: sampleIds.messages.venueAvailability,
    conversation: sampleIds.conversations.venue,
    type: 'availability_check',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Can you confirm October 16, 2027 specifically?',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
      },
      availability: {
        dateAvailable: 'yes',
        alternateDates: '2027-10-09 or 2027-10-23 if needed',
      },
    },
    inReplyTo: sampleIds.messages.venueInquiry,
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorVenue],
  },
  {
    id: sampleIds.messages.venueQuoteReq,
    conversation: sampleIds.conversations.venue,
    type: 'quote_request',
    sender: sampleIds.users.coupleJordan,
    senderRole: 'couple',
    body: 'Please send a formal site-fee quote including rehearsal add-on.',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Ceremony + reception site with rehearsal add-on.',
        budgetAllocation: 13000,
      },
    },
    readBy: [sampleIds.users.coupleJordan, sampleIds.users.vendorVenue],
  },
  {
    id: sampleIds.messages.venueQuote,
    conversation: sampleIds.conversations.venue,
    type: 'quote_response',
    sender: sampleIds.users.vendorVenue,
    senderRole: 'vendor',
    body: 'Quote attached for exclusive Saturday use.',
    structuredPayload: {
      quote: {
        currency: 'USD',
        subtotal: 12750,
        tax: 0,
        total: 12750,
        depositAmount: 3000,
        validUntil: '2026-08-01',
        inclusions: '10-hour exclusive use, bridal suite, parking attendants, rehearsal hour.',
        exclusions: 'Catering, rentals, alcohol, overnight lodging.',
        lineItems: [
          {
            name: 'Site fee',
            description: 'Ceremony lawn + pavilion',
            quantity: 1,
            unitPrice: 12000,
            amount: 12000,
          },
          {
            name: 'Rehearsal add-on',
            description: '2 hours evening before',
            quantity: 1,
            unitPrice: 750,
            amount: 750,
          },
        ],
      },
    },
    attachments: [sampleIds.media.quotePdf],
    readBy: [sampleIds.users.vendorVenue, sampleIds.users.coupleAlex],
  },
  {
    id: sampleIds.messages.venueClarify,
    conversation: sampleIds.conversations.venue,
    type: 'clarification',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Can we drop the rehearsal add-on and keep the base site fee?',
    structuredPayload: {
      quote: {
        currency: 'USD',
        total: 12000,
      },
    },
    inReplyTo: sampleIds.messages.venueQuote,
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorVenue],
  },
  {
    id: sampleIds.messages.venueBookReq,
    conversation: sampleIds.conversations.venue,
    type: 'booking_request',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'We would like to book the base site fee at $12,000.',
    structuredPayload: {
      booking: {
        acceptedTotal: 12000,
        depositDue: 3000,
        depositDueDate: '2026-07-25',
        termsSummary: 'Deposit due within 7 days; balance due 30 days before event.',
      },
    },
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorVenue],
  },
  {
    id: sampleIds.messages.venueBookConfirm,
    conversation: sampleIds.conversations.venue,
    type: 'booking_confirmation',
    sender: sampleIds.users.vendorVenue,
    senderRole: 'vendor',
    body: 'You are confirmed for October 16, 2027.',
    structuredPayload: {
      booking: {
        acceptedTotal: 12000,
        depositDue: 3000,
        depositDueDate: '2026-07-25',
        termsSummary: 'Deposit non-refundable after 14 days; rain plan included.',
        confirmationCode: 'OAKS-2027-1016',
      },
    },
    readBy: [
      sampleIds.users.vendorVenue,
      sampleIds.users.coupleAlex,
      sampleIds.users.coupleJordan,
    ],
  },
  {
    id: sampleIds.messages.venueSystem,
    conversation: sampleIds.conversations.venue,
    type: 'system',
    senderRole: 'system',
    body: 'Event debt created for confirmed venue booking.',
    structuredPayload: {
      system: {
        code: 'event_debt_created',
        payload: {
          paymentId: sampleIds.payments.venueDebt,
          amount: 12000,
        },
      },
    },
    readBy: [sampleIds.users.coupleAlex],
  },
  {
    id: sampleIds.messages.floristInquiry,
    conversation: sampleIds.conversations.florist,
    type: 'inquiry',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Looking for foam-free garden florals for an October estate wedding.',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Arch, bridal party, 12 centerpieces.',
        budgetAllocation: 4000,
        styleNotes: 'Peach garden roses, sage foliage, loose garden style.',
      },
    },
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorFlorist],
  },
  {
    id: sampleIds.messages.floristQuote,
    conversation: sampleIds.conversations.florist,
    type: 'quote_response',
    sender: sampleIds.users.vendorFlorist,
    senderRole: 'vendor',
    structuredPayload: {
      quote: {
        currency: 'USD',
        subtotal: 3800,
        tax: 0,
        total: 3800,
        depositAmount: 1500,
        validUntil: '2026-08-15',
        inclusions: 'Arch, bouquets x2, boutonnières x6, 12 centerpieces, delivery/setup.',
        exclusions: 'Ceremony chairs, linens.',
        lineItems: [
          { name: 'Ceremony arch', quantity: 1, unitPrice: 900, amount: 900 },
          { name: 'Personal flowers', quantity: 1, unitPrice: 1100, amount: 1100 },
          { name: 'Centerpieces', quantity: 12, unitPrice: 150, amount: 1800 },
        ],
      },
    },
    readBy: [sampleIds.users.vendorFlorist],
  },
  {
    id: sampleIds.messages.floristRevision,
    conversation: sampleIds.conversations.florist,
    type: 'quote_revision',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Can we reduce to 10 centerpieces?',
    structuredPayload: {
      quote: {
        currency: 'USD',
        total: 3500,
        inclusions: 'Arch, personal flowers, 10 centerpieces, delivery/setup.',
        lineItems: [
          { name: 'Ceremony arch', quantity: 1, unitPrice: 900, amount: 900 },
          { name: 'Personal flowers', quantity: 1, unitPrice: 1100, amount: 1100 },
          { name: 'Centerpieces', quantity: 10, unitPrice: 150, amount: 1500 },
        ],
      },
    },
    inReplyTo: sampleIds.messages.floristQuote,
    readBy: [sampleIds.users.coupleAlex],
  },
  {
    id: sampleIds.messages.photoInquiry,
    conversation: sampleIds.conversations.photo,
    type: 'inquiry',
    sender: sampleIds.users.coupleJordan,
    senderRole: 'couple',
    body: 'Interested in full-day documentary coverage.',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Full-day photo, two shooters.',
        budgetAllocation: 5500,
      },
    },
    readBy: [sampleIds.users.coupleJordan, sampleIds.users.vendorPhoto],
  },
  {
    id: sampleIds.messages.photoQuote,
    conversation: sampleIds.conversations.photo,
    type: 'quote_response',
    sender: sampleIds.users.vendorPhoto,
    senderRole: 'vendor',
    body: 'Full-day package quote below.',
    structuredPayload: {
      quote: {
        currency: 'USD',
        subtotal: 5200,
        tax: 0,
        total: 5200,
        depositAmount: 1500,
        validUntil: '2026-09-01',
        inclusions: '10 hours, two photographers, online gallery, print release, engagement session.',
        exclusions: 'Albums, second-day coverage.',
        lineItems: [
          {
            name: 'Full-day coverage',
            quantity: 1,
            unitPrice: 5200,
            amount: 5200,
          },
        ],
      },
    },
    readBy: [sampleIds.users.vendorPhoto],
  },
  {
    id: sampleIds.messages.musicInquiry,
    conversation: sampleIds.conversations.declinedMusic,
    type: 'inquiry',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Checking DJ availability for October 2027.',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Ceremony mics + reception DJ.',
        budgetAllocation: 2500,
      },
    },
    readBy: [sampleIds.users.coupleAlex, sampleIds.users.vendorMusic],
  },
  {
    id: sampleIds.messages.musicDecline,
    conversation: sampleIds.conversations.declinedMusic,
    type: 'decline',
    sender: sampleIds.users.vendorMusic,
    senderRole: 'vendor',
    body: 'That Saturday is already held.',
    structuredPayload: {
      decline: {
        reasonCode: 'date_unavailable',
        note: 'Booked through 2027-10-23. Happy to recommend another DJ.',
      },
      availability: {
        dateAvailable: 'no',
        alternateDates: '2027-10-30',
      },
    },
    inReplyTo: sampleIds.messages.musicInquiry,
    readBy: [sampleIds.users.vendorMusic, sampleIds.users.coupleAlex],
  },
  {
    id: sampleIds.messages.catererInquiry,
    conversation: sampleIds.conversations.caterer,
    type: 'inquiry',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    body: 'Exploring plated dinner + open bar for ~140 guests.',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        serviceSummary: 'Plated dinner and 5-hour open bar.',
        budgetAllocation: 14000,
        styleNotes: 'Seasonal Texas menu; vegetarian + GF options.',
      },
    },
    readBy: [sampleIds.users.coupleAlex],
  },
  {
    id: sampleIds.messages.catererAvail,
    conversation: sampleIds.conversations.caterer,
    type: 'availability_check',
    sender: sampleIds.users.coupleAlex,
    senderRole: 'couple',
    structuredPayload: {
      eventBrief: {
        weddingDate: '2027-10-16',
        guestCount: 140,
        venueName: 'Austin Oaks Estate',
        budgetAllocation: 14000,
      },
      availability: {
        dateAvailable: 'tentative',
        alternateDates: 'Holding soft until tasting scheduled',
      },
    },
    inReplyTo: sampleIds.messages.catererInquiry,
    readBy: [sampleIds.users.coupleAlex],
  },
]

/** Payments — debts, deposits, fees, payout, and a draft refund. */
export const samplePayments = [
  {
    id: sampleIds.payments.venueDebt,
    title: 'Austin Oaks Estate — event debt',
    kind: 'event_debt',
    status: 'partially_paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.oaks,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.venue,
    currency: 'USD',
    amount: 12000,
    amountPaid: 3000,
    amountDue: 9000,
    platformFee: 1200,
    platformFeeRate: 0.1,
    vendorNet: 10800,
    billingPeriod: '2026-07',
    dueDate: '2027-09-16',
    description: 'Confirmed venue booking for Oct 16, 2027.',
    lineItems: [
      { name: 'Site fee', amount: 12000, quantity: 1 },
    ],
    stripe: {
      customerId: 'cus_sample_alex',
      connectAccountId: 'acct_sample_oaks',
    },
  },
  {
    id: sampleIds.payments.venueDeposit,
    title: 'Austin Oaks Estate — deposit',
    kind: 'deposit',
    status: 'paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.oaks,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.venue,
    parentDebt: sampleIds.payments.venueDebt,
    currency: 'USD',
    amount: 3000,
    amountPaid: 3000,
    amountDue: 0,
    platformFee: 300,
    platformFeeRate: 0.1,
    vendorNet: 2700,
    billingPeriod: '2026-07',
    dueDate: '2026-07-25',
    description: 'Initial venue deposit.',
    stripe: {
      customerId: 'cus_sample_alex',
      paymentIntentId: 'pi_sample_venue_deposit',
      chargeId: 'ch_sample_venue_deposit',
      connectAccountId: 'acct_sample_oaks',
      latestEventId: 'evt_sample_venue_deposit',
    },
  },
  {
    id: sampleIds.payments.venueFee,
    title: 'Austin Oaks Estate — marketplace fee',
    kind: 'marketplace_fee',
    status: 'paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.oaks,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.venue,
    parentDebt: sampleIds.payments.venueDebt,
    currency: 'USD',
    amount: 300,
    amountPaid: 300,
    amountDue: 0,
    platformFee: 300,
    platformFeeRate: 0.1,
    vendorNet: 0,
    billingPeriod: '2026-07',
    description: 'Platform commission on venue deposit.',
  },
  {
    id: sampleIds.payments.venuePayout,
    title: 'Austin Oaks Estate — vendor payout',
    kind: 'vendor_payout',
    status: 'paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.oaks,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    parentDebt: sampleIds.payments.venueDebt,
    currency: 'USD',
    amount: 2700,
    amountPaid: 2700,
    amountDue: 0,
    vendorNet: 2700,
    billingPeriod: '2026-07',
    description: 'Connect transfer for collected deposit (net of fee).',
    stripe: {
      transferId: 'tr_sample_oaks_deposit',
      connectAccountId: 'acct_sample_oaks',
    },
  },
  {
    id: sampleIds.payments.floristDebt,
    title: 'Petal & Stem — event debt',
    kind: 'event_debt',
    status: 'partially_paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.petal,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.florist,
    currency: 'USD',
    amount: 3500,
    amountPaid: 1500,
    amountDue: 2000,
    platformFee: 350,
    platformFeeRate: 0.1,
    vendorNet: 3150,
    billingPeriod: '2026-07',
    dueDate: '2027-09-16',
    description: 'Confirmed florist package (revised to 10 centerpieces).',
    lineItems: [
      { name: 'Ceremony arch', amount: 900, quantity: 1 },
      { name: 'Personal flowers', amount: 1100, quantity: 1 },
      { name: 'Centerpieces', amount: 1500, quantity: 10 },
    ],
    stripe: {
      customerId: 'cus_sample_alex',
      connectAccountId: 'acct_sample_petal',
    },
  },
  {
    id: sampleIds.payments.floristDeposit,
    title: 'Petal & Stem — deposit',
    kind: 'deposit',
    status: 'paid',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.petal,
    couple: [sampleIds.users.coupleAlex],
    conversation: sampleIds.conversations.florist,
    parentDebt: sampleIds.payments.floristDebt,
    currency: 'USD',
    amount: 1500,
    amountPaid: 1500,
    amountDue: 0,
    platformFee: 150,
    platformFeeRate: 0.1,
    vendorNet: 1350,
    billingPeriod: '2026-07',
    dueDate: '2026-07-28',
    stripe: {
      customerId: 'cus_sample_alex',
      paymentIntentId: 'pi_sample_florist_deposit',
      chargeId: 'ch_sample_florist_deposit',
      connectAccountId: 'acct_sample_petal',
    },
  },
  {
    id: sampleIds.payments.photoDebt,
    title: 'True Lens Studio — event debt',
    kind: 'event_debt',
    status: 'due',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.lens,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.photo,
    currency: 'USD',
    amount: 5200,
    amountPaid: 0,
    amountDue: 5200,
    platformFee: 520,
    platformFeeRate: 0.1,
    vendorNet: 4680,
    billingPeriod: '2026-07',
    dueDate: '2026-09-01',
    description: 'Quoted photography package (not yet deposited).',
    lineItems: [{ name: 'Full-day coverage', amount: 5200, quantity: 1 }],
    stripe: {
      customerId: 'cus_sample_alex',
      connectAccountId: 'acct_sample_lens',
    },
  },
  {
    id: sampleIds.payments.photoRefundDraft,
    title: 'True Lens Studio — refund (draft)',
    kind: 'refund',
    status: 'draft',
    wedding: sampleIds.weddings.alexJordan,
    vendor: sampleIds.vendors.lens,
    couple: [sampleIds.users.coupleAlex, sampleIds.users.coupleJordan],
    conversation: sampleIds.conversations.photo,
    parentDebt: sampleIds.payments.photoDebt,
    currency: 'USD',
    amount: 0,
    amountPaid: 0,
    amountDue: 0,
    billingPeriod: '2026-07',
    description: 'Placeholder refund row if couple cancels before deposit.',
  },
]

export const sampleData = {
  media: sampleMedia,
  users: sampleUsers,
  vendors: sampleVendors,
  weddings: sampleWeddings,
  guests: sampleGuests,
  conversations: sampleConversations,
  messages: sampleMessages,
  payments: samplePayments,
}

export default sampleData
